name: server # Actions名称
on:
  # 触发workflow的动作形式，这里是手动触发
  workflow_dispatch:
  # [push]
  # push:
  #   branches:
  #     - master
  #   # 修改文件范围, 不在范围内不触发
  #   paths:
  #     - '.github/workflows/**'
  #     - '__test__/**'
  #     - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
      go-version: 1.17

    # 安装依赖
    - name: Get dependencies
      run: |
        cd server
        go mod download

    # 打包
    - name: Build
      working-directory: ./server
      run: |
        go build -v .

    # 打包镜像推送到腾讯云容器镜像服务
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} hkccr.ccs.tencentyun.com --password=${{ secrets.DOCKER_PASSWORD }}
        docker build -f ./server/Dockerfile -t xiaorunshu-server:latest .
        docker tag xiaorunshu-server hkccr.ccs.tencentyun.com/xiaorunshu/xiaorunshu-server:latest
        docker push hkccr.ccs.tencentyun.com/xiaorunshu/xiaorunshu-server:latest
    # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码配置方式同容器镜像服务配置方式一样
    - name: ssh docker login
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: cd ~/xiaorunshu && sh server.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
